### ISSUE TITLE
[bug] library crashing for cpp code block

### ISSUE THREAD

**Issue by GorvGoyl** [souvikinator/notion-to-md#53] opened 2022-10-13 19:15 UTC
a cpp code block:
![screenshot 2022-10-14 at 00 43 49](https://user-images.githubusercontent.com/7106086/195689027-c410bac2-dfca-476f-a1b9-c2c8ec5be841.png)

Error:
![screenshot 2022-10-14 at 00 44 03](https://user-images.githubusercontent.com/7106086/195689111-3003e76e-6e86-4f00-9c5a-bbf3bedfb8e1.png)

**Comment by souvikinator** [comment] 2022-12-19 14:48
Tested the stuff locally. Everything looks fine:
![image](https://user-images.githubusercontent.com/64456160/208452125-92ef031d-6886-4249-8fa5-26587d66977d.png)

Even the generated markdown is being rendered properly as you can see in the image. The problem is not with `notion-to-md` it's maybe an issue related to the markdown parser you are using. (MDX in this case I believe)

**Comment by souvikinator** [comment] 2023-01-27 02:30
Closing the issue, cannot recreate the issues.

**Closed by souvikinator** 2023-01-27 02:30 UTC
