### ISSUE TITLE
Content in a second column is rendered as a code block

### ISSUE THREAD

**Issue by victornpb** [souvikinator/notion-to-md#29] opened 2022-05-09 23:29 UTC
If you convert this page for example:

https://www.notion.so/d17c100b8ca94ffbacc694306461c1d1
<img width="811" alt="image" src="https://user-images.githubusercontent.com/3372598/167514338-00461559-ef22-46b8-8fae-108cd8aa98dd.png">

Is rendered like this:
<img width="1872" alt="image" src="https://user-images.githubusercontent.com/3372598/167514477-931bdb0d-ea15-4588-89a1-e27e613c4d45.png">

I know markdown doesn't support columns but I think it makes more sense to render the column as just inline content.

Also should image caption be used as img alt?

**Comment by souvikinator** [comment] 2022-05-10 20:49
Hey there, thanks for reporting. Due to certain issues, the indentation of the block is wrong which is why it is being rendered as a code block. 

I will fix and create a new release.

**About the issue related to image caption:**  it is already implemented, here is the pr https://github.com/souvikinator/notion-to-md/pull/12 . Try updating `notion-to-md` to the latest version. (`v2.3.2`)

**Comment by souvikinator** [comment] 2022-05-11 12:02
@victornpb the issue is now fixed in `v2.3.3`
Feel free to reopen the issue for further questions.

**Closed by souvikinator** 2022-05-11 12:02 UTC
Labels: bug

**Comment by victornpb** [comment] 2022-05-12 01:34
thank you!
